global using System.ComponentModel;
global using HealthCareAgent.Brain.Options;
global using HealthCareAgent.Brain.Plugins.FunctionPlugins;
global using HealthCareAgent.DataLayer;
global using HealthCareAgent.DataLayer.Options;
global using Microsoft.SemanticKernel;
global using Microsoft.SemanticKernel.ChatCompletion;
global using Microsoft.SemanticKernel.Connectors.Google;
global using Microsoft.SemanticKernel.Connectors.OpenAI;
